## <font size=4> *Métodos Numéricos II*, 2023 </font>
## <font size=3 color='gray'> Alan Reyes-Figueroa </font>

In [1]:
import numpy as np
from scipy import linalg as lg

In [2]:
from LLT_LDLT import Cholesky, LDLt

# Descomposición de Cholesky

In [3]:
M = np.array([[8.,7,9,5], [7,3,3,1], [9,3,1,0], [5,1,0,8]])
print(M)

[[8. 7. 9. 5.]
 [7. 3. 3. 1.]
 [9. 3. 1. 0.]
 [5. 1. 0. 8.]]


In [4]:
l, _ = lg.eigh(M)
l[::-1]

array([19.51028473,  7.02715293, -0.38784518, -6.14959247])

In [5]:
R = Cholesky(M)

Exception: matrix is not positive definite

In [6]:
A = np.array([[4.,-1,1], [-1,4.25,2.75], [1,2.75, 3.5]])
print(A)

[[ 4.   -1.    1.  ]
 [-1.    4.25  2.75]
 [ 1.    2.75  3.5 ]]


In [7]:
l, _ = lg.eigh(A)
l[::-1]

array([6.65444415, 4.5693526 , 0.52620325])

In [8]:
R = Cholesky(A)

In [9]:
R

array([[ 2. ,  0. ,  0. ],
       [-0.5,  2. ,  0. ],
       [ 0.5,  1.5,  1. ]])

In [10]:
R.T

array([[ 2. , -0.5,  0.5],
       [ 0. ,  2. ,  1.5],
       [ 0. ,  0. ,  1. ]])

In [11]:
R @ R.T

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [12]:
B = np.array([[6.,15,55], [15,55,225], [55,225,979]])
print(B)

[[  6.  15.  55.]
 [ 15.  55. 225.]
 [ 55. 225. 979.]]


In [13]:
l, _ = lg.eigh(B)
l[::-1]

array([1.03403287e+03, 5.24424641e+00, 7.22884035e-01])

In [14]:
R = Cholesky(B)

In [15]:
R

array([[ 2.44948974,  0.        ,  0.        ],
       [ 6.12372436,  4.18330013,  0.        ],
       [22.45365598, 20.91650066,  6.11010093]])

In [16]:
R @ R.T

array([[  6.,  15.,  55.],
       [ 15.,  55., 225.],
       [ 55., 225., 979.]])

In [17]:
np.linalg.cholesky(A)

array([[ 2. ,  0. ,  0. ],
       [-0.5,  2. ,  0. ],
       [ 0.5,  1.5,  1. ]])

In [18]:
np.linalg.cholesky(B)

array([[ 2.44948974,  0.        ,  0.        ],
       [ 6.12372436,  4.18330013,  0.        ],
       [22.45365598, 20.91650066,  6.11010093]])

In [19]:
L, D = LDLt(A)

In [20]:
print(L)

[[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.25  0.75  1.  ]]


In [21]:
print(D)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 1.]]


In [22]:
L @ D @ L.T

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [23]:
L, D = LDLt(B)

In [24]:
L

array([[1.        , 0.        , 0.        ],
       [2.5       , 1.        , 0.        ],
       [9.16666667, 5.        , 1.        ]])

In [25]:
D

array([[ 6.        ,  0.        ,  0.        ],
       [ 0.        , 17.5       ,  0.        ],
       [ 0.        ,  0.        , 37.33333333]])

In [26]:
L @ D @ L.T

array([[  6.,  15.,  55.],
       [ 15.,  55., 225.],
       [ 55., 225., 979.]])

In [27]:
C = np.array([[8.,1,2,4], [1,6,1,3], [2,1,5,0], [4,3,0,7]])
print(C)

[[8. 1. 2. 4.]
 [1. 6. 1. 3.]
 [2. 1. 5. 0.]
 [4. 3. 0. 7.]]


In [28]:
l, _ = lg.eigh(C)
l[::-1]

array([13.05517529,  6.03679177,  5.07560269,  1.83243025])

In [29]:
R = Cholesky(C)

In [30]:
R @ R.T

array([[ 8.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         4.00000000e+00],
       [ 1.00000000e+00,  6.00000000e+00,  1.00000000e+00,
         3.00000000e+00],
       [ 2.00000000e+00,  1.00000000e+00,  5.00000000e+00,
        -2.17922286e-16],
       [ 4.00000000e+00,  3.00000000e+00, -2.17922286e-16,
         7.00000000e+00]])

In [31]:
L, D = LDLt(C)

In [32]:
print(L)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.25000000e-01  1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 2.50000000e-01  1.27659574e-01  1.00000000e+00  0.00000000e+00]
 [ 5.00000000e-01  4.25531915e-01 -2.99516908e-01  1.00000000e+00]]


In [33]:
print(D)

[[8.         0.         0.         0.        ]
 [0.         5.875      0.         0.        ]
 [0.         0.         4.40425532 0.        ]
 [0.         0.         0.         3.5410628 ]]


In [34]:
np.round(L @ D @ L.T, 4)

array([[8., 1., 2., 4.],
       [1., 6., 1., 3.],
       [2., 1., 5., 0.],
       [4., 3., 0., 7.]])

## Determinar si una matriz es Positiva Definida

In [35]:
from LLT_LDLT import isPositive

In [36]:
isPositive(A)

True

In [37]:
isPositive(M)

False

In [38]:
S, V = lg.eig(A)

In [39]:
A

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [40]:
V @ np.diag(np.abs(S)) @ V.T

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

## Hallar la matriz Definida Positiva más cercana

In [41]:
def nearestPositive(A, eps=1e-16):
    m, n = A.shape
    if (m != n):
        raise Exception('matrix is not square')
    elif not np.all(A.T == A):
        raise Exception('matrix is not symmetric')
    else:
        S, V = lg.eig(A)
        S = np.real(S)
        S[S <= 0.] = eps  # cambiar autovalores negativos a eps
    return V @ np.diag(S) @ V.T

In [42]:
A

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [43]:
Ap = nearestPositive(A, 1e-8)

In [44]:
Ap

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [45]:
C = A.copy()
C[0,0] = 0.
C

array([[ 0.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [46]:
isPositive(C)

False

In [47]:
Cp = nearestPositive(C, eps=1e-16)

In [48]:
Cp

array([[ 0.65800151, -0.69809371,  0.666712  ],
       [-0.69809371,  4.38852157,  2.59707977],
       [ 0.666712  ,  2.59707977,  3.66881556]])

In [49]:
M

array([[8., 7., 9., 5.],
       [7., 3., 3., 1.],
       [9., 3., 1., 0.],
       [5., 1., 0., 8.]])

In [50]:
isPositive(M)

False

In [51]:
Mp = nearestPositive(M, eps=1e-8)

In [52]:
Mp

array([[10.51436149,  6.01411779,  6.28004385,  4.18040176],
       [ 6.01411779,  3.61765605,  3.85415527,  1.30789699],
       [ 6.28004385,  3.85415527,  4.13747347,  0.89899033],
       [ 4.18040176,  1.30789699,  0.89899033,  8.26794667]])

In [53]:
lM, VM = lg.eigh(M)

In [54]:
lM

array([-6.14959247, -0.38784518,  7.02715293, 19.51028473])

In [55]:
lMP, VMP = lg.eigh(Mp)

In [56]:
lMP

array([9.99999777e-09, 1.00000002e-08, 7.02715293e+00, 1.95102847e+01])

In [57]:
VM

array([[ 0.63725091,  0.209861  , -0.13085583,  0.72989478],
       [-0.2338886 , -0.85156276, -0.2329282 ,  0.40728545],
       [-0.70403906,  0.4798369 , -0.31133889,  0.42089625],
       [-0.20865378, -0.02357485,  0.91197001,  0.35244648]])

In [58]:
VMP

array([[ 0.22356913,  0.6325719 , -0.13085583, -0.72989478],
       [-0.85641352, -0.21545046, -0.2329282 , -0.40728545],
       [ 0.4645262 , -0.71423376, -0.31133889, -0.42089625],
       [-0.0280738 , -0.20809622,  0.91197001, -0.35244648]])