## <font size=4> *Métodos Numéricos II*, 2023 </font>
## <font size=3 color='gray'> Alan Reyes-Figueroa </font>

In [1]:
import numpy as np
from scipy import linalg as lg

# Ejemplos de matrices deficientes (*defective*)

In [2]:
A = np.array([[2.,0,0], [0,2,0], [0,0,2]])
B = np.array([[2.,1,0], [0,2,1], [0,0,2]])
C = np.array([[2.,0,1], [0,3,0], [0,0,1]])

print(A, end='\n\n')
print(B, end='\n\n')
print(C)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]

[[2. 1. 0.]
 [0. 2. 1.]
 [0. 0. 2.]]

[[2. 0. 1.]
 [0. 3. 0.]
 [0. 0. 1.]]


## Ejemplo A

In [3]:
print(A)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


In [4]:
# descomposición espectral
SA, XA = lg.eig(A)

print(SA, end='\n\n')
print(XA)

[2.+0.j 2.+0.j 2.+0.j]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
np.diag(np.real(SA))

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [6]:
# SA es un vector complejo, np.real calcula la parte real a cada componente
np.real(SA)

array([2., 2., 2.])

In [7]:
# reconstruimos la matrix A como A = XSX^{-1}
# como no es defectuosa, resulta en la A original

recA = XA @ np.diag(np.real(SA)) @ np.linalg.inv(XA)
recA

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

## Ejemplo B

In [8]:
print(B)

[[2. 1. 0.]
 [0. 2. 1.]
 [0. 0. 2.]]


In [9]:
SB, XB = lg.eig(B)

print(SB, end='\n\n')
print(XB)

[2.+0.j 2.+0.j 2.+0.j]

[[ 1.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  4.44089210e-16 -4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  1.97215226e-31]]


In [10]:
# reconstruimos la matrix B como B = XSX^{-1}
# como es defectuosa, resulta diferente de la B original

recB = (XB) @ np.diag(np.real(SB)) @ (XB.T)
recB

array([[ 6.00000000e+00, -1.77635684e-15,  3.94430453e-31],
       [-1.77635684e-15,  7.88860905e-31, -1.75162308e-46],
       [ 3.94430453e-31, -1.75162308e-46,  7.77876910e-62]])

In [11]:
np.round(recB, 3)

array([[ 6., -0.,  0.],
       [-0.,  0., -0.],
       [ 0., -0.,  0.]])

## Ejemplo C

In [12]:
print(C)

[[2. 0. 1.]
 [0. 3. 0.]
 [0. 0. 1.]]


In [13]:
SC, XC = lg.eig(C)

print(SC, end='\n\n')
print(XC)

[2.+0.j 3.+0.j 1.+0.j]

[[ 1.          0.         -0.70710678]
 [ 0.          1.          0.        ]
 [ 0.          0.          0.70710678]]


In [14]:
# reconstruimos la matrix C como C = XSX^{-1}
# como es defectuosa, resulta diferente de la C original

recC = XC @ np.diag(np.real(SC)) @ np.linalg.inv(XC)
recC

array([[2., 0., 1.],
       [0., 3., 0.],
       [0., 0., 1.]])

## Forma rápida de verificar si A es diagonalizable

In [15]:
A

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [16]:
SA, XA = lg.eig(A)

In [17]:
XA

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# X^T X debe ser una matriz de rango completo (rango 3 en este caso)

XA.T @ XA

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
B

array([[2., 1., 0.],
       [0., 2., 1.],
       [0., 0., 2.]])

In [20]:
SB, XB = lg.eig(B)

In [21]:
XB

array([[ 1.00000000e+00, -1.00000000e+00,  1.00000000e+00],
       [ 0.00000000e+00,  4.44089210e-16, -4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.97215226e-31]])

In [22]:
XB @ XB.T

array([[ 3.00000000e+00, -8.88178420e-16,  1.97215226e-31],
       [-8.88178420e-16,  3.94430453e-31, -8.75811540e-47],
       [ 1.97215226e-31, -8.75811540e-47,  3.88938455e-62]])

In [23]:
# X^T X no es diagonal, entonces B es defectuosa

XB.T @ XB

array([[ 1., -1.,  1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.]])

In [24]:
(XC.T) @ XC    # XC^T XC  sí es de rango completo

array([[ 1.        ,  0.        , -0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       [-0.70710678,  0.        ,  1.        ]])