## <font size=4> *Métodos Numéricos II*, 2023 </font>
## <font size=3 color='gray'> Alan Reyes-Figueroa </font>

In [1]:
import numpy as np
from scipy import linalg as lg

# Descomposición SVD

In [2]:
A = np.array([[2.,0,0], [0,2,0], [0,0,2]])
B = np.array([[2.,1,0], [0,2,1], [0,0,2]])
C = np.array([[2.,0,1], [0,3,0], [0,0,1]])

print(A, end='\n\n')
print(B, end='\n\n')
print(C)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]

[[2. 1. 0.]
 [0. 2. 1.]
 [0. 0. 2.]]

[[2. 0. 1.]
 [0. 3. 0.]
 [0. 0. 1.]]


In [3]:
# Descomposición SVD:  C = USV^T

U, S, V = lg.svd(B)

In [4]:
print(U, end='\n\n')
print(np.diag(S), end='\n\n')
print(V)                          # Aquí V les guarda la V^T

[[ 0.55480803 -0.71709346  0.42185901]
 [ 0.72851788  0.17384567 -0.66260047]
 [ 0.4018081   0.67494789  0.61886638]]

[[2.76155718 0.         0.        ]
 [0.         2.12488542 0.        ]
 [0.         0.         1.36332824]]

[[ 0.4018081   0.72851788  0.55480803]
 [-0.67494789 -0.17384567  0.71709346]
 [ 0.61886638 -0.66260047  0.42185901]]


In [5]:
recB = U @ np.diag(S) @ V
recB

array([[ 2.00000000e+00,  1.00000000e+00, -7.45719202e-16],
       [-9.28010775e-16,  2.00000000e+00,  1.00000000e+00],
       [-1.06956137e-15, -7.26870515e-16,  2.00000000e+00]])

In [6]:
np.round(recB, 4)

array([[ 2.,  1., -0.],
       [-0.,  2.,  1.],
       [-0., -0.,  2.]])

In [7]:
X = np.array([[5, 0, 2], [7, 3, 5], [-4, 1, 0], [3, -1, -2]])
X

array([[ 5,  0,  2],
       [ 7,  3,  5],
       [-4,  1,  0],
       [ 3, -1, -2]])

In [8]:
U, S, V = lg.svd(X)

In [9]:
U

array([[-0.48100974,  0.18479081,  0.57428191, -0.63614643],
       [-0.80821037, -0.43457194, -0.36627893,  0.15421732],
       [ 0.30607206, -0.51110555, -0.36926711, -0.71325508],
       [-0.14746367,  0.71817178, -0.63220395, -0.25060314]])

In [10]:
S

array([10.98677289,  4.60882821,  1.02446277])

In [11]:
S = np.hstack([S, np.array([0])])
S

array([10.98677289,  4.60882821,  1.02446277,  0.        ])

In [12]:
np.diag(S)[:,:-1]

array([[10.98677289,  0.        ,  0.        ],
       [ 0.        ,  4.60882821,  0.        ],
       [ 0.        ,  0.        ,  1.02446277],
       [ 0.        ,  0.        ,  0.        ]])

In [13]:
V

array([[-0.8855376 , -0.17940622, -0.42852838],
       [ 0.45150044, -0.54959591, -0.70291655],
       [-0.10940985, -0.81593979,  0.56768983]])

In [14]:
U @ np.diag(S)[:,:-1] @ V

array([[ 5.00000000e+00,  1.07505616e-15,  2.00000000e+00],
       [ 7.00000000e+00,  3.00000000e+00,  5.00000000e+00],
       [-4.00000000e+00,  1.00000000e+00,  4.66426444e-16],
       [ 3.00000000e+00, -1.00000000e+00, -2.00000000e+00]])

In [15]:
U, S, V = lg.svd(X, full_matrices=False)

In [16]:
U

array([[-0.48100974,  0.18479081,  0.57428191],
       [-0.80821037, -0.43457194, -0.36627893],
       [ 0.30607206, -0.51110555, -0.36926711],
       [-0.14746367,  0.71817178, -0.63220395]])

In [17]:
S

array([10.98677289,  4.60882821,  1.02446277])

In [18]:
V

array([[-0.8855376 , -0.17940622, -0.42852838],
       [ 0.45150044, -0.54959591, -0.70291655],
       [-0.10940985, -0.81593979,  0.56768983]])

## Descomposición de Schur

In [19]:
# Descomposición de Schur:  C = QTQ^T

T, Q = lg.schur(C)

In [20]:
print(Q, end='\n\n')
print(T)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[2. 0. 1.]
 [0. 3. 0.]
 [0. 0. 1.]]


In [21]:
recC = Q @ T @ Q.T
recC

array([[2., 0., 1.],
       [0., 3., 0.],
       [0., 0., 1.]])

In [22]:
D = np.array([[2.,0,0], [0,3,0], [1,0,1]])
D

array([[2., 0., 0.],
       [0., 3., 0.],
       [1., 0., 1.]])

In [23]:
T, Q = lg.schur(D)

In [24]:
print(Q, end='\n\n')
print(T)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

[[1. 1. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [25]:
recD = Q @ T @ Q.T
recD

array([[2., 0., 0.],
       [0., 3., 0.],
       [1., 0., 1.]])